twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_5_layout.html.twig', '/form/theme/fields.html.twig' ]
  globals:
    copyright_year: '%env(COPYRIGHT_YEAR)%'
    company: '%env(COMPANY)%'
    company_website: '%env(COMPANY_WEBSITE)%'

when@test:
  twig:
    strict_variables: true
