version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql-db
    command:
      - "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: nX7N6ZmdaC7AUKwf
      MYSQL_ROOT_HOST: "%"
